### ISSUE TITLE
Issue 3 Using ORM

### ISSUE THREAD

**Issue by NCFindley** [NCFindley/pokemon_database#3]
"I'm currently having issue using/understanding ORM find method for Stats class (pokedex.rb file) running my tests. I'm receiving no defined method.

1. test_find_record test is failing
2. When calling the Stats.find(id,table) function i receive error that no such method exist.
3. My understanding is when using exclude ClassMethodsORM in the class it should be able to call the self.find method using Stats.find(variables)

Expected to receive the instance of the new class with variables populated from the select statement. 

Actual : The test fails and nothing happens. I receive error no such method 'find'

**Comment by sumeetjain** [comment]
My fault. Remove the `self.` from the method names in the module. I totally goofed on that in my lecture. Sorry!
